services:
  api:
    build:
      context: .
      dockerfile: src/CriatorioVirtual.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "${API_PORT:-8080}:8080"
