// <auto-generated />
using System;
using CriatorioVirtual.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CriatorioVirtual.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CriatorioVirtualDbContext))]
    [Migration("20260911162316_RegisterReproduction")]
    partial class RegisterReproduction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CriatorioVirtual.Domain.Birds.Bird", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid>("BreedingFarmId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date");

                    b.Property<string>("ExternalFatherName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ExternalFatherSex")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalMotherName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ExternalMotherSex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FatherBirdId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MotherBirdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RingNumber")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("BreedingFarmId", "Id")
                        .HasName("ak_birds_farm_id");

                    b.HasIndex("RingNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_birds_ring_number")
                        .HasFilter("\"RingNumber\" IS NOT NULL");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("BreedingFarmId", "FatherBirdId");

                    b.HasIndex("BreedingFarmId", "MotherBirdId");

                    b.HasIndex("BreedingFarmId", "Status")
                        .HasDatabaseName("ix_birds_farm_status");

                    b.ToTable("birds", "app", t =>
                        {
                            t.HasCheckConstraint("ck_birds_death_date_after_birth_date", "\"DeathDate\" IS NULL OR \"BirthDate\" IS NULL OR \"DeathDate\" >= \"BirthDate\"");

                            t.HasCheckConstraint("ck_birds_external_father_sex", "\"ExternalFatherSex\" IS NULL OR (\"ExternalFatherName\" IS NOT NULL AND \"ExternalFatherSex\" = 1)");

                            t.HasCheckConstraint("ck_birds_external_mother_sex", "\"ExternalMotherSex\" IS NULL OR (\"ExternalMotherName\" IS NOT NULL AND \"ExternalMotherSex\" = 2)");

                            t.HasCheckConstraint("ck_birds_father_source_exclusive", "\"FatherBirdId\" IS NULL OR \"ExternalFatherName\" IS NULL");

                            t.HasCheckConstraint("ck_birds_mother_source_exclusive", "\"MotherBirdId\" IS NULL OR \"ExternalMotherName\" IS NULL");

                            t.HasCheckConstraint("ck_birds_name_not_blank", "btrim(\"Name\") <> ''");

                            t.HasCheckConstraint("ck_birds_ring_number_format", "\"RingNumber\" IS NULL OR \"RingNumber\" ~ '^[0-9]{6}$'");

                            t.HasCheckConstraint("ck_birds_sex_valid", "\"Sex\" IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_birds_status_valid", "\"Status\" IN (1, 2, 3, 4, 5)");
                        });
                });

            modelBuilder.Entity("CriatorioVirtual.Domain.Birds.GenealogyNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BirdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BreedingFarmId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GenealogyRootId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRoot")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LinkedBirdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("SnapshotBirthDate")
                        .HasColumnType("date");

                    b.Property<string>("SnapshotName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SnapshotRingNumber")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int?>("SnapshotSex")
                        .HasColumnType("integer");

                    b.Property<int?>("SnapshotStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BirdId")
                        .IsUnique()
                        .HasDatabaseName("ux_genealogy_nodes_bird_root")
                        .HasFilter("\"IsRoot\" = TRUE");

                    b.HasIndex("BreedingFarmId", "BirdId");

                    b.HasIndex("BreedingFarmId", "LinkedBirdId");

                    b.HasIndex("GenealogyRootId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_genealogy_nodes_root_position");

                    b.ToTable("genealogy_nodes", "app", t =>
                        {
                            t.HasCheckConstraint("ck_genealogy_nodes_root_position", "(\"IsRoot\" = TRUE AND \"Position\" = 'root' AND \"LinkedBirdId\" = \"BirdId\") OR (\"IsRoot\" = FALSE AND \"BreedingFarmId\" IS NOT NULL AND \"Position\" <> 'root' AND \"LinkedBirdId\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_genealogy_nodes_snapshot_required", "\"IsRoot\" = TRUE OR (\"SnapshotName\" IS NOT NULL AND \"SnapshotSex\" IS NOT NULL AND \"SnapshotStatus\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CriatorioVirtual.Domain.BreedingFarms.BreedingFarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OfficialRegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResponsibleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OfficialRegistrationNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_breeding_farms_official_registration_number")
                        .HasFilter("\"OfficialRegistrationNumber\" IS NOT NULL");

                    b.ToTable("breeding_farms", "app", t =>
                        {
                            t.HasCheckConstraint("ck_breeding_farms_name_not_blank", "btrim(\"Name\") <> ''");

                            t.HasCheckConstraint("ck_breeding_farms_official_registration_not_blank", "\"OfficialRegistrationNumber\" IS NULL OR btrim(\"OfficialRegistrationNumber\") <> ''");
                        });
                });

            modelBuilder.Entity("CriatorioVirtual.Domain.BreedingFarms.BreedingFarmUser", b =>
                {
                    b.Property<Guid>("BreedingFarmId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("BreedingFarmId", "UserId");

                    b.HasIndex("BreedingFarmId")
                        .IsUnique()
                        .HasDatabaseName("ux_breeding_farm_users_active_owner")
                        .HasFilter("\"IsActive\" = TRUE AND \"Role\" = 1");

                    b.HasIndex("UserId");

                    b.ToTable("breeding_farm_users", "app", t =>
                        {
                            t.HasCheckConstraint("ck_breeding_farm_users_role_valid", "\"Role\" IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("CriatorioVirtual.Domain.Reproductions.Reproduction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BreedingFarmId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FemaleBirdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaleBirdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BreedingFarmId", "FemaleBirdId");

                    b.HasIndex("BreedingFarmId", "MaleBirdId", "FemaleBirdId")
                        .HasDatabaseName("ix_reproductions_farm_pair");

                    b.HasIndex("BreedingFarmId", "Status", "StartDate")
                        .HasDatabaseName("ix_reproductions_farm_status_start_date");

                    b.ToTable("reproductions", "app", t =>
                        {
                            t.HasCheckConstraint("ck_reproductions_date_range", "\"EndDate\" IS NULL OR \"EndDate\" >= \"StartDate\"");

                            t.HasCheckConstraint("ck_reproductions_distinct_birds", "\"MaleBirdId\" <> \"FemaleBirdId\"");

                            t.HasCheckConstraint("ck_reproductions_status_valid", "\"Status\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("CriatorioVirtual.Domain.Species.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedPopularName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedScientificName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PopularName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedPopularName", "NormalizedScientificName")
                        .IsUnique()
                        .HasDatabaseName("ux_species_normalized_names");

                    b.ToTable("species", "app", t =>
                        {
                            t.HasCheckConstraint("ck_species_popular_name_not_blank", "btrim(\"PopularName\") <> ''");

                            t.HasCheckConstraint("ck_species_scientific_name_not_blank", "btrim(\"ScientificName\") <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "CURIO",
                            NormalizedScientificName = "SPOROPHILA ANGOLENSIS",
                            PopularName = "Curió",
                            ScientificName = "Sporophila angolensis",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "BICUDO - VERDADEIRO",
                            NormalizedScientificName = "SPOROPHILA MAXIMILIANI",
                            PopularName = "Bicudo - verdadeiro",
                            ScientificName = "Sporophila maximiliani",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "CARDEAL",
                            NormalizedScientificName = "PAROARIA CORONATA",
                            PopularName = "Cardeal",
                            ScientificName = "Paroaria coronata",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "GALO-DA-CAMPINA",
                            NormalizedScientificName = "PAROARIA DOMINICANA",
                            PopularName = "Galo-da-campina",
                            ScientificName = "Paroaria dominicana",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "AZULAO-DA-AMAZONIA",
                            NormalizedScientificName = "PASSERINA CYANOIDES",
                            PopularName = "Azulão-da-amazônia",
                            ScientificName = "Passerina cyanoides",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "CANARIO-DA-TERRA",
                            NormalizedScientificName = "SICALIS FLAVEOLA BRASILIENSIS",
                            PopularName = "Canário-da-terra",
                            ScientificName = "Sicalis flaveola brasiliensis",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "COLEIRO-PAPA-CAPIM",
                            NormalizedScientificName = "SPOROPHILA CAERULESCENS",
                            PopularName = "Coleiro-papa-capim",
                            ScientificName = "Sporophila caerulescens",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "BIGODINHO",
                            NormalizedScientificName = "SPOROPHILA LINEOLA",
                            PopularName = "Bigodinho",
                            ScientificName = "Sporophila lineola",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "PICHOCHO",
                            NormalizedScientificName = "SPOROPHILA FRONTALIS",
                            PopularName = "Pichochó",
                            ScientificName = "Sporophila frontalis",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "COLEIRO-BAIANO",
                            NormalizedScientificName = "SPOROPHILA NIGRICOLLIS",
                            PopularName = "Coleiro-baiano",
                            ScientificName = "Sporophila nigricollis",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "TICO-TICO",
                            NormalizedScientificName = "ZONOTRICHIA CAPENSIS",
                            PopularName = "Tico-tico",
                            ScientificName = "Zonotrichia capensis",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "BICUDO-PANTANEIRO",
                            NormalizedScientificName = "SPOROPHILA MAXIMILIANI GIGANTIROSTRIS",
                            PopularName = "Bicudo-pantaneiro",
                            ScientificName = "Sporophila maximiliani gigantirostris",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "BICUDO-DO-BICO-PRETO",
                            NormalizedScientificName = "SPOROPHILA MAXIMILIANI ATRIROSTRIS",
                            PopularName = "Bicudo-do-bico-preto",
                            ScientificName = "Sporophila maximiliani atrirostris",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "TICO-TICO-REI",
                            NormalizedScientificName = "CORYPHOSPINGUS CUCULLATUS",
                            PopularName = "Tico-tico-rei",
                            ScientificName = "Coryphospingus cucullatus",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "COLEIRO-DO-BREJO",
                            NormalizedScientificName = "SPOROPHILA COLLARIS",
                            PopularName = "Coleiro-do-brejo",
                            ScientificName = "Sporophila collaris",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "PATATIVA-VERDADEIRA",
                            NormalizedScientificName = "SPOROPHILA PLUMBEA",
                            PopularName = "Patativa-verdadeira",
                            ScientificName = "Sporophila plumbea",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "TICO-TICO-REI-CINZA",
                            NormalizedScientificName = "CORYPHOSPINGUS PILEATUS",
                            PopularName = "Tico-tico-rei-cinza",
                            ScientificName = "Coryphospingus pileatus",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "CIGARRA-RAINHA",
                            NormalizedScientificName = "SPOROPHILA LEUCOPTERA",
                            PopularName = "Cigarra-rainha",
                            ScientificName = "Sporophila leucoptera",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "CIGARRA-VERDADEIRA",
                            NormalizedScientificName = "SPOROPHILA FALCIROSTRIS",
                            PopularName = "Cigarra-verdadeira",
                            ScientificName = "Sporophila falcirostris",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "CANARIO-CHAPINHA",
                            NormalizedScientificName = "SICALIS FLAVEOLA PELZELNI",
                            PopularName = "Canário-chapinha",
                            ScientificName = "Sicalis flaveola pelzelni",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "TIZIU",
                            NormalizedScientificName = "VOLATINIA JACARINA",
                            PopularName = "Tiziu",
                            ScientificName = "Volatinia jacarina",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "CARDEAL-AMARELO",
                            NormalizedScientificName = "GUBERNATRIX CRISTATA",
                            PopularName = "Cardeal-amarelo",
                            ScientificName = "Gubernatrix cristata",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "CABOCLINHO-DE-PAPO-ESCURO",
                            NormalizedScientificName = "SPOROPHILA RUFICOLLIS",
                            PopularName = "Caboclinho-de-papo-escuro",
                            ScientificName = "Sporophila ruficollis",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "CABOCLINHO",
                            NormalizedScientificName = "SPOROPHILA BOUVREUIL",
                            PopularName = "Caboclinho",
                            ScientificName = "Sporophila bouvreuil",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "CIGARRA-BAMBU",
                            NormalizedScientificName = "HAPLOSPIZA UNICOLOR",
                            PopularName = "Cigarra-bambu",
                            ScientificName = "Haplospiza unicolor",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "CABOCLINHO-LINDO",
                            NormalizedScientificName = "SPOROPHILA MINUTA",
                            PopularName = "Caboclinho-lindo",
                            ScientificName = "Sporophila minuta",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "GOLINHO",
                            NormalizedScientificName = "SPOROPHILA ALBOGULARIS",
                            PopularName = "Golinho",
                            ScientificName = "Sporophila albogularis",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "BICUDINHO",
                            NormalizedScientificName = "SPOROPHILA CRASSIROSTRIS",
                            PopularName = "Bicudinho",
                            ScientificName = "Sporophila crassirostris",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "CORRUPIAO",
                            NormalizedScientificName = "ICTERUS JAMACAII",
                            PopularName = "Corrupião",
                            ScientificName = "Icterus jamacaii",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "GRAUNA",
                            NormalizedScientificName = "GNORIMOPSAR CHOPI",
                            PopularName = "Graúna",
                            ScientificName = "Gnorimopsar chopi",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "IRAUNA-GRANDE",
                            NormalizedScientificName = "MOLOTHRUS ORYZIVORUS",
                            PopularName = "Iraúna-grande",
                            ScientificName = "Molothrus oryzivorus",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "SARGENTO",
                            NormalizedScientificName = "AGELASTICUS THILIUS",
                            PopularName = "Sargento",
                            ScientificName = "Agelasticus thilius",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "TECELAO",
                            NormalizedScientificName = "CACICUS CHRYSOPTERUS",
                            PopularName = "Tecelão",
                            ScientificName = "Cacicus chrysopterus",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "XEXEU",
                            NormalizedScientificName = "CACICUS CELA",
                            PopularName = "Xexéu",
                            ScientificName = "Cacicus cela",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "AZULAO VERDADEIRO",
                            NormalizedScientificName = "CYANOLOXIA BRISSONII",
                            PopularName = "Azulão verdadeiro",
                            ScientificName = "Cyanoloxia brissonii",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "PIMENTAO",
                            NormalizedScientificName = "SALTATOR FULIGINOSUS",
                            PopularName = "Pimentão",
                            ScientificName = "Saltator fuliginosus",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "TRINCA-FERRO-VERDADEIRO",
                            NormalizedScientificName = "SALTATOR SIMILIS",
                            PopularName = "Trinca-ferro-verdadeiro",
                            ScientificName = "Saltator similis",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "BICO-DURO",
                            NormalizedScientificName = "SALTATOR AURANTIIROSTRIS",
                            PopularName = "Bico-duro",
                            ScientificName = "Saltator aurantiirostris",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "AZULINHO",
                            NormalizedScientificName = "CYANOLOXIA GLAUCOCAERULEA",
                            PopularName = "Azulinho",
                            ScientificName = "Cyanoloxia glaucocaerulea",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "BICO-DE-PIMENTA",
                            NormalizedScientificName = "SALTATOR ATRICOLLIS",
                            PopularName = "Bico-de-pimenta",
                            ScientificName = "Saltator atricollis",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "PINTASSILGO",
                            NormalizedScientificName = "CARDUELIS MAGELLANICUS",
                            PopularName = "Pintassilgo",
                            ScientificName = "Carduelis magellanicus",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "PINTASSILGO-DO-NORDESTE",
                            NormalizedScientificName = "CARDUELIS YARRELLII",
                            PopularName = "Pintassilgo-do-nordeste",
                            ScientificName = "Carduelis yarrellii",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "GATURAMO-DE-BICO-GROSSO",
                            NormalizedScientificName = "EUPHONIA LANIIROSTRIS",
                            PopularName = "Gaturamo-de-bico-grosso",
                            ScientificName = "Euphonia laniirostris",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000044"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "CARACHUE-COLEIRA SABIA",
                            NormalizedScientificName = "TURDUS ALBICOLLIS",
                            PopularName = "Carachué-coleira sabiá",
                            ScientificName = "Turdus albicollis",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000045"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "SABIA-POCA",
                            NormalizedScientificName = "TURDUS AMAUROCHALINUS",
                            PopularName = "Sabiá-pocá",
                            ScientificName = "Turdus amaurochalinus",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000046"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "SABIA-DA-MATA",
                            NormalizedScientificName = "TURDUS FUMIGATUS",
                            PopularName = "Sabiá-da-mata",
                            ScientificName = "Turdus fumigatus",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000047"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "SABIA-LARANJEIRA",
                            NormalizedScientificName = "TURDUS RUFIVENTRIS",
                            PopularName = "Sabiá-laranjeira",
                            ScientificName = "Turdus rufiventris",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000048"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "SABIA-BARRANCO",
                            NormalizedScientificName = "TURDUS LEUCOMELAS",
                            PopularName = "Sabiá-barranco",
                            ScientificName = "Turdus leucomelas",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000049"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "SABIA-UNA",
                            NormalizedScientificName = "TURDUS FLAVIPES",
                            PopularName = "Sabiá-una",
                            ScientificName = "Turdus flavipes",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "SANHACO-FRADE",
                            NormalizedScientificName = "STEPHANOPHORUS DIADEMATUS",
                            PopularName = "Sanhaço-frade",
                            ScientificName = "Stephanophorus diadematus",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000051"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "SANHACO-CINZENTO",
                            NormalizedScientificName = "THRAUPIS SAYACA",
                            PopularName = "Sanhaço-cinzento",
                            ScientificName = "Thraupis sayaca",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000052"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "TEMPERA-VIOLA",
                            NormalizedScientificName = "SALTATOR MAXIMUS",
                            PopularName = "Tempera-viola",
                            ScientificName = "Saltator maximus",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000053"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "BICO-DE-VELUDO",
                            NormalizedScientificName = "SCHISTOCHLAMYS RUFICAPILLUS",
                            PopularName = "Bico-de-veludo",
                            ScientificName = "Schistochlamys ruficapillus",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000054"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "TIE-SANGUE",
                            NormalizedScientificName = "RAMPHOCELUS BRESILIUS",
                            PopularName = "Tiê-sangue",
                            ScientificName = "Ramphocelus bresilius",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000055"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "SANHACO-DA-AMAZONIA",
                            NormalizedScientificName = "THRAUPIS EPISCOPUS",
                            PopularName = "Sanhaço-da-amazônia",
                            ScientificName = "Thraupis episcopus",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000056"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "TIE-PRETO",
                            NormalizedScientificName = "TACHYPHONUS CORONATUS",
                            PopularName = "Tiê-preto",
                            ScientificName = "Tachyphonus coronatus",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000057"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "SAIRA-SETE-CORES",
                            NormalizedScientificName = "TANGARA SELEDON",
                            PopularName = "Saíra-sete-cores",
                            ScientificName = "Tangara seledon",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000058"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "SANHACO-DO-COQUEIRO",
                            NormalizedScientificName = "THRAUPIS PALMARUM",
                            PopularName = "Sanhaço-do-coqueiro",
                            ScientificName = "Thraupis palmarum",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000059"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "SANHACO-DE-COLEIRA",
                            NormalizedScientificName = "SCHISTOCHLAMYS MELANOPIS",
                            PopularName = "Sanhaço-de-coleira",
                            ScientificName = "Schistochlamys melanopis",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000060"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            NormalizedPopularName = "SABIA-DO-CAMPO",
                            NormalizedScientificName = "MIMUS SATURNINUS",
                            PopularName = "Sabiá-do-campo",
                            ScientificName = "Mimus saturninus",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("CriatorioVirtual.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<Guid?>("SelectedBreedingFarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("SelectedBreedingFarmId");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("\"NormalizedEmail\" IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("SelectedBreedingFarmId");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("data_protection_keys", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", "identity");
                });

            modelBuilder.Entity("CriatorioVirtual.Domain.Birds.Bird", b =>
                {
                    b.HasOne("CriatorioVirtual.Domain.BreedingFarms.BreedingFarm", null)
                        .WithMany()
                        .HasForeignKey("BreedingFarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CriatorioVirtual.Domain.Species.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriatorioVirtual.Domain.Birds.Bird", null)
                        .WithMany()
                        .HasForeignKey("BreedingFarmId", "FatherBirdId")
                        .HasPrincipalKey("BreedingFarmId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CriatorioVirtual.Domain.Birds.Bird", null)
                        .WithMany()
                        .HasForeignKey("BreedingFarmId", "MotherBirdId")
                        .HasPrincipalKey("BreedingFarmId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CriatorioVirtual.Domain.Birds.GenealogyNode", b =>
                {
                    b.HasOne("CriatorioVirtual.Domain.Birds.GenealogyNode", null)
                        .WithMany()
                        .HasForeignKey("GenealogyRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CriatorioVirtual.Domain.Birds.Bird", null)
                        .WithMany()
                        .HasForeignKey("BreedingFarmId", "BirdId")
                        .HasPrincipalKey("BreedingFarmId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CriatorioVirtual.Domain.Birds.Bird", null)
                        .WithMany()
                        .HasForeignKey("BreedingFarmId", "LinkedBirdId")
                        .HasPrincipalKey("BreedingFarmId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CriatorioVirtual.Domain.BreedingFarms.BreedingFarm", b =>
                {
                    b.OwnsOne("CriatorioVirtual.Domain.BreedingFarms.BreedingFarmAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("BreedingFarmId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("AddressCity");

                            b1.Property<string>("Complement")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("AddressComplement");

                            b1.Property<string>("Neighborhood")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("AddressNeighborhood");

                            b1.Property<string>("Number")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("AddressNumber");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("AddressPostalCode");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("AddressState");

                            b1.Property<string>("Street")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("AddressStreet");

                            b1.HasKey("BreedingFarmId");

                            b1.ToTable("breeding_farms", "app");

                            b1.WithOwner()
                                .HasForeignKey("BreedingFarmId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("CriatorioVirtual.Domain.BreedingFarms.BreedingFarmUser", b =>
                {
                    b.HasOne("CriatorioVirtual.Domain.BreedingFarms.BreedingFarm", null)
                        .WithMany()
                        .HasForeignKey("BreedingFarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CriatorioVirtual.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CriatorioVirtual.Domain.Reproductions.Reproduction", b =>
                {
                    b.HasOne("CriatorioVirtual.Domain.BreedingFarms.BreedingFarm", null)
                        .WithMany()
                        .HasForeignKey("BreedingFarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CriatorioVirtual.Domain.Birds.Bird", null)
                        .WithMany()
                        .HasForeignKey("BreedingFarmId", "FemaleBirdId")
                        .HasPrincipalKey("BreedingFarmId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriatorioVirtual.Domain.Birds.Bird", null)
                        .WithMany()
                        .HasForeignKey("BreedingFarmId", "MaleBirdId")
                        .HasPrincipalKey("BreedingFarmId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriatorioVirtual.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.HasOne("CriatorioVirtual.Domain.BreedingFarms.BreedingFarm", null)
                        .WithMany()
                        .HasForeignKey("SelectedBreedingFarmId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CriatorioVirtual.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CriatorioVirtual.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CriatorioVirtual.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CriatorioVirtual.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
