<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\src\CriatorioVirtual.Infrastructure\CriatorioVirtual.Infrastructure.csproj" />
  </ItemGroup>
</Project>
